### ISSUE TITLE
missing proc

### ISSUE THREAD

**Issue by seadba** [tanelpoder/psnapper#8]
hi, ive used this utility before, many times -its great -thanks

i downloaded the current version, getting this message - im sure it somthing stupid imdoing or not, but cant figure it  out

/tmp/psnapper-master/bin# ./psn
Traceback (most recent call last):
  File "./psn", line 31, in <module>
    import proc, psnreport
ImportError: No module named proc
root@linux4:/tmp/psnapper-master/bin#

**Comment by tanelpoder** [comment]
Thanks for the feedback. I'm working on updating to a new version and pushed the code yesterday (haven't announced anything yet). I guess I'll need to test the new directory layout some more. Let me test in a new clean VM and I'll get back.

Oh, when did you pull the latest code? I pushed the "latest latest code" yesterday evening (less than 24 hrs ago)

**Comment by tanelpoder** [comment]
It may be something silly on my part (regarding including the libraries from their new locations). If you `cd ..` (to the root directory of this repo) and run `./bin/psn`, does it work as a temporary workaround?

**Comment by seadba** [comment]
Just 3hrs ago.

**Comment by seadba** [comment]
Will test when i get home. Thanks

**Comment by tanelpoder** [comment]
Yeah I already found a mistake - hardcoded path that I intended to replace, but had forgotten. I'll fix now & let you know

**Comment by tanelpoder** [comment]
Ok, I fixed the silly bug and pushed the fix. Before I announce the new version, I'll run this through my manual test suite too (on CentOS 5/6/7/8 and a couple of Ubuntu/Debian versions). These tests would have exposed this bug, but you got there first! 

Let me know if it works now.

Also I'd be interested in hearing any success stories with pSnapper (over email is fine or here to)

**Comment by seadba** [comment]
all good - thanks - 



[root@linux1 bin]# psn -G syscall,wchan -r

Linux Process Snapper v0.18 by Tanel Poder [https://0x.tools]
Sampling /proc/wchan, syscall, stat for 5 seconds... finished.


=== Active Threads ===========================================================================================

 samples | avg_threads | comm              | state                  | syscall         | wchan
--------------------------------------------------------------------------------------------------------------
      12 |        0.75 | (postgres)        | Running (ON CPU)       | [running]       | 0
       5 |        0.31 | (ksoftirqd/*)     | Running (ON CPU)       | [running]       | 0
       4 |        0.25 | (sqlservr)        | Running (ON CPU)       | [running]       | 0
       4 |        0.25 | (sshd)            | Running (ON CPU)       | [running]       | 0
       3 |        0.19 | (postgres)        | Disk (Uninterruptible) | rename          | wait_on_page_bit
       3 |        0.19 | (postgres)        | Running (ON CPU)       | epoll_wait      | ep_poll
       2 |        0.12 | (kworker/*:*)     | Running (ON CPU)       | [kernel_thread] | worker_thread
       2 |        0.12 | (mysqld)          | Running (ON CPU)       | [running]       | 0
       2 |        0.12 | (pgbench)         | Running (ON CPU)       | [running]       | 0

**Comment by tanelpoder** [comment]
Cool, thanks for letting me know. `sqlserver` on Linux, nice :-)

**Comment by seadba** [comment]
thanks for the fast fix  - i wouldn't have noticed until you mentioned sqlserver - that pgbench process at the end - i haven't run pgbench on that server in months - curious - no need to re-open ticket - thanks again
